Readme
apojomovsky/mpu6050-dmp-ros-raspberry pull request #7
Opened 2024-04-24 20:35 UTC by Felipegalind0

This command fails if you do not have IMU tools for ROS installed
'rosdep install --from-paths src --ignore-src -r -y'

I updated the readme with the link to their repo

Also updated 

    topic_name = rospy.get_param('~/imu_publisher/topic_name', 'imu_data')
    frame_id = rospy.get_param('~/imu_publisher/frame_id', 'base_link')
    i2c_bus = rospy.get_param('~/imu_publisher/i2c_bus', 1)
    device_address = rospy.get_param('~/imu_publisher/device_address', 0x68)
    x_accel_offset = rospy.get_param('~/imu_publisher/x_accel_offset', 0)
    y_accel_offset = rospy.get_param('~/imu_publisher/y_accel_offset', 0)
    z_accel_offset = rospy.get_param('~/imu_publisher/z_accel_offset', 0)
    x_gyro_offset = rospy.get_param('~/imu_publisher/x_gyro_offset', 0)
    y_gyro_offset = rospy.get_param('~/imu_publisher/y_gyro_offset', 0)
    z_gyro_offset = rospy.get_param('~/imu_publisher/z_gyro_offset', 0)

the '/imu_publisher/' were missing and default values were being used

2024-04-24 20:59 UTC, apojomovsky commented
Hey @Felipegalind0 , thanks for the contribution. Looks like I missed the node namespace in the rosparams.

Have some concerns about this though:

> This command fails if you do not have IMU tools for ROS installed
'rosdep install --from-paths src --ignore-src -r -y'

This problem you're describing seems a bit off to me, as imu_tools is currently handled via rosdep. So, assuming your rosdep setup is correctly initialized, the command above should be taking care of the installation of the package as it is a direct dependency of rviz_imu_plugin, which is correctly tracked in the package.xml [here](https://github.com/apojomovsky/mpu6050-dmp-ros-raspberry/blob/noetic-devel/package.xml#L22). PTAL.

So as a first think I'd suggest you to double check your rosdep initialization. If you happen to still run into this issue, I might be able to help you pinpoint the root cause.

As a general rule I'd say that if the package exists in rosdep, that'd always be the preferred way to install it.

2024-04-25 19:32 UTC, Felipegalind0 commented
Thank you for helping me figure this out @apojomovsky, I'm still learning how to use ROS properly to please forgive me if I am missing something. 

I am testing this on a VS code Dev container on a Raspberry Pi 5, I rebuilt my container (removing imu_tools) so that I can try running the command again and share the output with you:

First I tried running the command:

`rosdep install --from-paths src --ignore-src -r -y`

As you can see I get a warning: 

`mpu6050_dmp_ros: Cannot locate rosdep definition for [rviz_imu_plugin]` :

```
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ rosdep install --from-paths src --ignore-src -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
mini_ros: Cannot locate rosdep definition for [hector_sensors_description]
mpu6050_dmp_ros: Cannot locate rosdep definition for [rviz_imu_plugin]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

<br>
Next I tried running `sudo rosdep init` and `rosdep update`, but that did not fix it. The warning is still there:

```
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ sudo rosdep init
ERROR: default sources list file already exists:
        /etc/ros/rosdep/sources.list.d/20-default.list
Please delete if you wish to re-initialize
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Skip end-of-life distro "foxy"
Skip end-of-life distro "galactic"
Skip end-of-life distro "groovy"
Add distro "humble"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Add distro "iron"
Skip end-of-life distro "jade"
Add distro "jazzy"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Skip end-of-life distro "melodic"
Add distro "noetic"
Add distro "rolling"
updated cache in /home/vscode/.ros/rosdep/sources.cache
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ rosdep install --from-paths src --ignore-src -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
mini_ros: Cannot locate rosdep definition for [hector_sensors_description]
mpu6050_dmp_ros: Cannot locate rosdep definition for [rviz_imu_plugin]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

Only after I run 'sudo apt-get install ros-melodic-imu-tools' it finally goes away:

```
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ sudo apt-get install ros-melodic-imu-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done

...

Setting up libassimp-dev:arm64 (4.1.0~dfsg-3) ...
Setting up ros-melodic-rviz (1.13.30-1bionic.20230330.122946) ...
Setting up ros-melodic-rviz-imu-plugin (1.2.5-1bionic.20230330.141711) ...
Setting up ros-melodic-imu-tools (1.2.5-1bionic.20230330.152135) ...
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ rosdep install --from-paths src --ignore-src -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
m[ntinuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

This is the repo for my dev container, in case you want to take a look at something on my system:
[https://github.com/UMN-VR/spot_mini_mini/tree/gdogV11](https://github.com/UMN-VR/spot_mini_mini/tree/gdogV11)

2024-04-25 21:04 UTC, apojomovsky commented
@Felipegalind0 from the first part of your terminal output:
```
(spot_mini_env) vscode@gdogv10:~/catkin_ws$ sudo rosdep init
ERROR: default sources list file already exists:
        /etc/ros/rosdep/sources.list.d/20-default.list
Please delete if you wish to re-initialize
```

Looks like your rosdep initialization failed and you went ahead with the update anyways. This could well be the reason, as docker images may come with an already-initilized rosdep that has expired keys.

Please try the following:
- Delete the `/etc/ros/rosdep/sources.list.d/20-default.list`  file
- Re-run the initialization and update of rosdep
- Try installing dependencies again

Let me know how it goes.

2024-04-28 18:29 UTC, apojomovsky requested changes
Please attend the requested suggestions, I'll be merging afterwards. Thanks

2024-04-28 18:29 UTC, apojomovsky commented on README.md
> +0. **Install IMU Tools:**
Please remove these changes from the readme

2024-04-28 18:29 UTC, apojomovsky commented on scripts/imu_publisher
> +    print(f"mpu = MPU6050(i2c_bus={i2c_bus}, device_address={device_address}, x_accel_offset={x_accel_offset}, y_accel_offset={y_accel_offset}, z_accel_offset={z_accel_offset}, x_gyro_offset={x_gyro_
Please remove these debug statements

2024-05-08 14:34 UTC, apojomovsky commented
Gentle ping @Felipegalind0

2024-05-28 01:53 UTC, Felipegalind0 commented
Sorry for late reply,

I removed the debug statement, and cleaned up the README 

Thank you for your guidance

2024-05-28 02:41 UTC, apojomovsky reviewed
LGTM, thanks

2024-05-28 02:42 UTC, apojomovsky approved these changes

2024-05-28 02:42 UTC, merged